// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: proto/hqssh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_RUNNING     SessionStatus = 1
	SessionStatus_SESSION_STATUS_IDLE        SessionStatus = 2
	SessionStatus_SESSION_STATUS_ENDED       SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_IDLE",
		3: "SESSION_STATUS_ENDED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_RUNNING":     1,
		"SESSION_STATUS_IDLE":        2,
		"SESSION_STATUS_ENDED":       3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hqssh_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_proto_hqssh_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{0}
}

type TaskScope int32

const (
	TaskScope_TASK_SCOPE_UNSPECIFIED TaskScope = 0
	TaskScope_TASK_SCOPE_GLOBAL      TaskScope = 1 // Runs on any system
	TaskScope_TASK_SCOPE_SYSTEM      TaskScope = 2 // Runs on this system, no project context
	TaskScope_TASK_SCOPE_PROJECT     TaskScope = 3 // Runs in project directory
)

// Enum value maps for TaskScope.
var (
	TaskScope_name = map[int32]string{
		0: "TASK_SCOPE_UNSPECIFIED",
		1: "TASK_SCOPE_GLOBAL",
		2: "TASK_SCOPE_SYSTEM",
		3: "TASK_SCOPE_PROJECT",
	}
	TaskScope_value = map[string]int32{
		"TASK_SCOPE_UNSPECIFIED": 0,
		"TASK_SCOPE_GLOBAL":      1,
		"TASK_SCOPE_SYSTEM":      2,
		"TASK_SCOPE_PROJECT":     3,
	}
)

func (x TaskScope) Enum() *TaskScope {
	p := new(TaskScope)
	*p = x
	return p
}

func (x TaskScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hqssh_proto_enumTypes[1].Descriptor()
}

func (TaskScope) Type() protoreflect.EnumType {
	return &file_proto_hqssh_proto_enumTypes[1]
}

func (x TaskScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskScope.Descriptor instead.
func (TaskScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{1}
}

type TaskRunStatus int32

const (
	TaskRunStatus_TASK_RUN_STATUS_UNSPECIFIED TaskRunStatus = 0
	TaskRunStatus_TASK_RUN_STATUS_PENDING     TaskRunStatus = 1
	TaskRunStatus_TASK_RUN_STATUS_RUNNING     TaskRunStatus = 2
	TaskRunStatus_TASK_RUN_STATUS_COMPLETED   TaskRunStatus = 3
	TaskRunStatus_TASK_RUN_STATUS_FAILED      TaskRunStatus = 4
	TaskRunStatus_TASK_RUN_STATUS_CANCELLED   TaskRunStatus = 5
)

// Enum value maps for TaskRunStatus.
var (
	TaskRunStatus_name = map[int32]string{
		0: "TASK_RUN_STATUS_UNSPECIFIED",
		1: "TASK_RUN_STATUS_PENDING",
		2: "TASK_RUN_STATUS_RUNNING",
		3: "TASK_RUN_STATUS_COMPLETED",
		4: "TASK_RUN_STATUS_FAILED",
		5: "TASK_RUN_STATUS_CANCELLED",
	}
	TaskRunStatus_value = map[string]int32{
		"TASK_RUN_STATUS_UNSPECIFIED": 0,
		"TASK_RUN_STATUS_PENDING":     1,
		"TASK_RUN_STATUS_RUNNING":     2,
		"TASK_RUN_STATUS_COMPLETED":   3,
		"TASK_RUN_STATUS_FAILED":      4,
		"TASK_RUN_STATUS_CANCELLED":   5,
	}
)

func (x TaskRunStatus) Enum() *TaskRunStatus {
	p := new(TaskRunStatus)
	*p = x
	return p
}

func (x TaskRunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskRunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hqssh_proto_enumTypes[2].Descriptor()
}

func (TaskRunStatus) Type() protoreflect.EnumType {
	return &file_proto_hqssh_proto_enumTypes[2]
}

func (x TaskRunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskRunStatus.Descriptor instead.
func (TaskRunStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{2}
}

// Common messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_hqssh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{0}
}

type SystemInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	DaemonVersion  string                 `protobuf:"bytes,4,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	InstalledTools []string               `protobuf:"bytes,5,rep,name=installed_tools,json=installedTools,proto3" json:"installed_tools,omitempty"` // ['claude', 'codex', 'aider']
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_hqssh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *SystemInfo) GetInstalledTools() []string {
	if x != nil {
		return x.InstalledTools
	}
	return nil
}

type SystemStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds  int64                  `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	ActiveProjects int32                  `protobuf:"varint,3,opt,name=active_projects,json=activeProjects,proto3" json:"active_projects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_proto_hqssh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{2}
}

func (x *SystemStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemStatus) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *SystemStatus) GetActiveProjects() int32 {
	if x != nil {
		return x.ActiveProjects
	}
	return 0
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	DetectedTools []string               `protobuf:"bytes,4,rep,name=detected_tools,json=detectedTools,proto3" json:"detected_tools,omitempty"`
	LastAccessed  int64                  `protobuf:"varint,5,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"` // Unix timestamp
	IsFavorite    bool                   `protobuf:"varint,6,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_hqssh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{3}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Project) GetDetectedTools() []string {
	if x != nil {
		return x.DetectedTools
	}
	return nil
}

func (x *Project) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

func (x *Project) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavoritesOnly bool                   `protobuf:"varint,1,opt,name=favorites_only,json=favoritesOnly,proto3" json:"favorites_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectsRequest) GetFavoritesOnly() bool {
	if x != nil {
		return x.FavoritesOnly
	}
	return false
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type AddProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Optional, defaults to directory name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectRequest) Reset() {
	*x = AddProjectRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectRequest) ProtoMessage() {}

func (x *AddProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectRequest.ProtoReflect.Descriptor instead.
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{6}
}

func (x *AddProjectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectRequest) Reset() {
	*x = RemoveProjectRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectRequest) ProtoMessage() {}

func (x *RemoveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directories   []string               `protobuf:"bytes,1,rep,name=directories,proto3" json:"directories,omitempty"`            // Directories to scan
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // Default: 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverRequest) GetDirectories() []string {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *DiscoverRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discovered    []*Project             `protobuf:"bytes,1,rep,name=discovered,proto3" json:"discovered,omitempty"`
	TotalScanned  int32                  `protobuf:"varint,2,opt,name=total_scanned,json=totalScanned,proto3" json:"total_scanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverResponse) GetDiscovered() []*Project {
	if x != nil {
		return x.Discovered
	}
	return nil
}

func (x *DiscoverResponse) GetTotalScanned() int32 {
	if x != nil {
		return x.TotalScanned
	}
	return 0
}

type GetToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolsRequest) Reset() {
	*x = GetToolsRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolsRequest) ProtoMessage() {}

func (x *GetToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolsRequest.ProtoReflect.Descriptor instead.
func (*GetToolsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{10}
}

func (x *GetToolsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []string               `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolsResponse) Reset() {
	*x = GetToolsResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolsResponse) ProtoMessage() {}

func (x *GetToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolsResponse.ProtoReflect.Descriptor instead.
func (*GetToolsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{11}
}

func (x *GetToolsResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId        string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Tool             string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"` // 'claude', 'codex', 'aider', 'shell'
	WorkingDirectory string                 `protobuf:"bytes,4,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Status           SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=hqssh.SessionStatus" json:"status,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // Unix timestamp
	LastActivity     int64                  `protobuf:"varint,7,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"` // Unix timestamp
	ClientCount      int32                  `protobuf:"varint,8,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`    // Number of attached clients
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_hqssh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{12}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Session) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Session) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *Session) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                      // Optional - if set, uses project directory
	Tool             string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`                                                 // 'claude', 'codex', 'aider', 'shell'
	WorkingDirectory string                 `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"` // Used if no project_id
	Args             []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                                                 // Additional tool arguments
	Cols             int32                  `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`                                                // Terminal columns
	Rows             int32                  `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`                                                // Terminal rows
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSessionRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CreateSessionRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *CreateSessionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateSessionRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreateSessionRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`           // Optional - filter by project
	IncludeEnded  bool                   `protobuf:"varint,2,opt,name=include_ended,json=includeEnded,proto3" json:"include_ended,omitempty"` // Include ended sessions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{14}
}

func (x *ListSessionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListSessionsRequest) GetIncludeEnded() bool {
	if x != nil {
		return x.IncludeEnded
	}
	return false
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{15}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{16}
}

func (x *AttachRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *AttachRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_proto_hqssh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{17}
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_proto_hqssh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{18}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DetachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachRequest) Reset() {
	*x = DetachRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachRequest) ProtoMessage() {}

func (x *DetachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachRequest.ProtoReflect.Descriptor instead.
func (*DetachRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{19}
}

func (x *DetachRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{20}
}

func (x *KillSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{21}
}

func (x *ResizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tool           string                 `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"` // 'claude', 'codex', 'aider'
	Scope          TaskScope              `protobuf:"varint,5,opt,name=scope,proto3,enum=hqssh.TaskScope" json:"scope,omitempty"`
	ProjectId      string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // Required if scope == PROJECT
	Prompt         string                 `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Interactive    bool                   `protobuf:"varint,8,opt,name=interactive,proto3" json:"interactive,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 for no timeout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_hqssh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{22}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Task) GetScope() TaskScope {
	if x != nil {
		return x.Scope
	}
	return TaskScope_TASK_SCOPE_UNSPECIFIED
}

func (x *Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *Task) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type TaskRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskRunStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=hqssh.TaskRunStatus" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // For interactive tasks - can attach
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRun) Reset() {
	*x = TaskRun{}
	mi := &file_proto_hqssh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRun) ProtoMessage() {}

func (x *TaskRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRun.ProtoReflect.Descriptor instead.
func (*TaskRun) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{23}
}

func (x *TaskRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRun) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRun) GetStatus() TaskRunStatus {
	if x != nil {
		return x.Status
	}
	return TaskRunStatus_TASK_RUN_STATUS_UNSPECIFIED
}

func (x *TaskRun) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TaskRun) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *TaskRun) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskRun) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         TaskScope              `protobuf:"varint,1,opt,name=scope,proto3,enum=hqssh.TaskScope" json:"scope,omitempty"`    // Optional - filter by scope
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // Optional - filter by project
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksRequest) GetScope() TaskScope {
	if x != nil {
		return x.Scope
	}
	return TaskScope_TASK_SCOPE_UNSPECIFIED
}

func (x *ListTasksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{25}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tool           string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Scope          TaskScope              `protobuf:"varint,4,opt,name=scope,proto3,enum=hqssh.TaskScope" json:"scope,omitempty"`
	ProjectId      string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,6,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Interactive    bool                   `protobuf:"varint,7,opt,name=interactive,proto3" json:"interactive,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{26}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CreateTaskRequest) GetScope() TaskScope {
	if x != nil {
		return x.Scope
	}
	return TaskScope_TASK_SCOPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *CreateTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type UpdateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tool           string                 `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"`
	Scope          TaskScope              `protobuf:"varint,5,opt,name=scope,proto3,enum=hqssh.TaskScope" json:"scope,omitempty"`
	ProjectId      string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Interactive    bool                   `protobuf:"varint,8,opt,name=interactive,proto3" json:"interactive,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *UpdateTaskRequest) GetScope() TaskScope {
	if x != nil {
		return x.Scope
	}
	return TaskScope_TASK_SCOPE_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTaskRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *UpdateTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{29}
}

func (x *RunTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{30}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // Optional - filter by task
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                // Default: 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{31}
}

func (x *ListRunsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*TaskRun             `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{32}
}

func (x *ListRunsResponse) GetRuns() []*TaskRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{33}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ExportTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTaskRequest) Reset() {
	*x = ExportTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskRequest) ProtoMessage() {}

func (x *ExportTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskRequest.ProtoReflect.Descriptor instead.
func (*ExportTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{34}
}

func (x *ExportTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ExportTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTaskResponse) Reset() {
	*x = ExportTaskResponse{}
	mi := &file_proto_hqssh_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskResponse) ProtoMessage() {}

func (x *ExportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskResponse.ProtoReflect.Descriptor instead.
func (*ExportTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{35}
}

func (x *ExportTaskResponse) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type ImportTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaml          string                 `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTaskRequest) Reset() {
	*x = ImportTaskRequest{}
	mi := &file_proto_hqssh_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTaskRequest) ProtoMessage() {}

func (x *ImportTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hqssh_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTaskRequest.ProtoReflect.Descriptor instead.
func (*ImportTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hqssh_proto_rawDescGZIP(), []int{36}
}

func (x *ImportTaskRequest) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

var File_proto_hqssh_proto protoreflect.FileDescriptor

const file_proto_hqssh_proto_rawDesc = "" +
	"\n" +
	"\x11proto/hqssh.proto\x12\x05hqssh\"\a\n" +
	"\x05Empty\"\x9c\x01\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12%\n" +
	"\x0edaemon_version\x18\x04 \x01(\tR\rdaemonVersion\x12'\n" +
	"\x0finstalled_tools\x18\x05 \x03(\tR\x0einstalledTools\"\x87\x01\n" +
	"\fSystemStatus\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12'\n" +
	"\x0factive_projects\x18\x03 \x01(\x05R\x0eactiveProjects\"\xae\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12%\n" +
	"\x0edetected_tools\x18\x04 \x03(\tR\rdetectedTools\x12#\n" +
	"\rlast_accessed\x18\x05 \x01(\x03R\flastAccessed\x12\x1f\n" +
	"\vis_favorite\x18\x06 \x01(\bR\n" +
	"isFavorite\"<\n" +
	"\x13ListProjectsRequest\x12%\n" +
	"\x0efavorites_only\x18\x01 \x01(\bR\rfavoritesOnly\"B\n" +
	"\x14ListProjectsResponse\x12*\n" +
	"\bprojects\x18\x01 \x03(\v2\x0e.hqssh.ProjectR\bprojects\";\n" +
	"\x11AddProjectRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x14RemoveProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"P\n" +
	"\x0fDiscoverRequest\x12 \n" +
	"\vdirectories\x18\x01 \x03(\tR\vdirectories\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"g\n" +
	"\x10DiscoverResponse\x12.\n" +
	"\n" +
	"discovered\x18\x01 \x03(\v2\x0e.hqssh.ProjectR\n" +
	"discovered\x12#\n" +
	"\rtotal_scanned\x18\x02 \x01(\x05R\ftotalScanned\"0\n" +
	"\x0fGetToolsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"(\n" +
	"\x10GetToolsResponse\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools\"\x8e\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12+\n" +
	"\x11working_directory\x18\x04 \x01(\tR\x10workingDirectory\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.hqssh.SessionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rlast_activity\x18\a \x01(\x03R\flastActivity\x12!\n" +
	"\fclient_count\x18\b \x01(\x05R\vclientCount\"\xb2\x01\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\"Y\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12#\n" +
	"\rinclude_ended\x18\x02 \x01(\bR\fincludeEnded\"B\n" +
	"\x14ListSessionsResponse\x12*\n" +
	"\bsessions\x18\x01 \x03(\v2\x0e.hqssh.SessionR\bsessions\"V\n" +
	"\rAttachRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"$\n" +
	"\x0eTerminalOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"B\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\".\n" +
	"\rDetachRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12KillSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"V\n" +
	"\rResizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"\x8a\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tool\x18\x04 \x01(\tR\x04tool\x12&\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x10.hqssh.TaskScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06prompt\x18\a \x01(\tR\x06prompt\x12 \n" +
	"\vinteractive\x18\b \x01(\bR\vinteractive\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\x05R\x0etimeoutSeconds\"\xef\x01\n" +
	"\aTaskRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.hqssh.TaskRunStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAt\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\"Y\n" +
	"\x10ListTasksRequest\x12&\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x10.hqssh.TaskScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"6\n" +
	"\x11ListTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.hqssh.TaskR\x05tasks\"\x87\x02\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12&\n" +
	"\x05scope\x18\x04 \x01(\x0e2\x10.hqssh.TaskScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06prompt\x18\x06 \x01(\tR\x06prompt\x12 \n" +
	"\vinteractive\x18\a \x01(\bR\vinteractive\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\"\x97\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tool\x18\x04 \x01(\tR\x04tool\x12&\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x10.hqssh.TaskScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06prompt\x18\a \x01(\tR\x06prompt\x12 \n" +
	"\vinteractive\x18\b \x01(\bR\vinteractive\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\x05R\x0etimeoutSeconds\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\")\n" +
	"\x0eRunTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"@\n" +
	"\x0fListRunsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"6\n" +
	"\x10ListRunsResponse\x12\"\n" +
	"\x04runs\x18\x01 \x03(\v2\x0e.hqssh.TaskRunR\x04runs\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\",\n" +
	"\x11ExportTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"(\n" +
	"\x12ExportTaskResponse\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\"'\n" +
	"\x11ImportTaskRequest\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml*~\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_ENDED\x10\x03*m\n" +
	"\tTaskScope\x12\x1a\n" +
	"\x16TASK_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_SCOPE_GLOBAL\x10\x01\x12\x15\n" +
	"\x11TASK_SCOPE_SYSTEM\x10\x02\x12\x16\n" +
	"\x12TASK_SCOPE_PROJECT\x10\x03*\xc4\x01\n" +
	"\rTaskRunStatus\x12\x1f\n" +
	"\x1bTASK_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_RUN_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_RUN_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19TASK_RUN_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16TASK_RUN_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19TASK_RUN_STATUS_CANCELLED\x10\x052k\n" +
	"\rSystemService\x12*\n" +
	"\aGetInfo\x12\f.hqssh.Empty\x1a\x11.hqssh.SystemInfo\x12.\n" +
	"\tGetStatus\x12\f.hqssh.Empty\x1a\x13.hqssh.SystemStatus2\xb1\x02\n" +
	"\x0eProjectService\x12?\n" +
	"\x04List\x12\x1a.hqssh.ListProjectsRequest\x1a\x1b.hqssh.ListProjectsResponse\x12/\n" +
	"\x03Add\x12\x18.hqssh.AddProjectRequest\x1a\x0e.hqssh.Project\x123\n" +
	"\x06Remove\x12\x1b.hqssh.RemoveProjectRequest\x1a\f.hqssh.Empty\x12;\n" +
	"\bDiscover\x12\x16.hqssh.DiscoverRequest\x1a\x17.hqssh.DiscoverResponse\x12;\n" +
	"\bGetTools\x12\x16.hqssh.GetToolsRequest\x1a\x17.hqssh.GetToolsResponse2\xfd\x02\n" +
	"\x0eSessionService\x125\n" +
	"\x06Create\x12\x1b.hqssh.CreateSessionRequest\x1a\x0e.hqssh.Session\x12?\n" +
	"\x04List\x12\x1a.hqssh.ListSessionsRequest\x1a\x1b.hqssh.ListSessionsResponse\x127\n" +
	"\x06Attach\x12\x14.hqssh.AttachRequest\x1a\x15.hqssh.TerminalOutput0\x01\x12-\n" +
	"\x05Input\x12\x14.hqssh.TerminalInput\x1a\f.hqssh.Empty(\x01\x12,\n" +
	"\x06Detach\x12\x14.hqssh.DetachRequest\x1a\f.hqssh.Empty\x12/\n" +
	"\x04Kill\x12\x19.hqssh.KillSessionRequest\x1a\f.hqssh.Empty\x12,\n" +
	"\x06Resize\x12\x14.hqssh.ResizeRequest\x1a\f.hqssh.Empty2\x9b\x04\n" +
	"\vTaskService\x129\n" +
	"\x04List\x12\x17.hqssh.ListTasksRequest\x1a\x18.hqssh.ListTasksResponse\x12/\n" +
	"\x06Create\x12\x18.hqssh.CreateTaskRequest\x1a\v.hqssh.Task\x12/\n" +
	"\x06Update\x12\x18.hqssh.UpdateTaskRequest\x1a\v.hqssh.Task\x120\n" +
	"\x06Delete\x12\x18.hqssh.DeleteTaskRequest\x1a\f.hqssh.Empty\x12,\n" +
	"\x03Run\x12\x15.hqssh.RunTaskRequest\x1a\x0e.hqssh.TaskRun\x12.\n" +
	"\x06GetRun\x12\x14.hqssh.GetRunRequest\x1a\x0e.hqssh.TaskRun\x12;\n" +
	"\bListRuns\x12\x16.hqssh.ListRunsRequest\x1a\x17.hqssh.ListRunsResponse\x122\n" +
	"\tCancelRun\x12\x17.hqssh.CancelRunRequest\x1a\f.hqssh.Empty\x12=\n" +
	"\x06Export\x12\x18.hqssh.ExportTaskRequest\x1a\x19.hqssh.ExportTaskResponse\x12/\n" +
	"\x06Import\x12\x18.hqssh.ImportTaskRequest\x1a\v.hqssh.TaskB!Z\x1fgithub.com/gelotto/hqsshd/protob\x06proto3"

var (
	file_proto_hqssh_proto_rawDescOnce sync.Once
	file_proto_hqssh_proto_rawDescData []byte
)

func file_proto_hqssh_proto_rawDescGZIP() []byte {
	file_proto_hqssh_proto_rawDescOnce.Do(func() {
		file_proto_hqssh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hqssh_proto_rawDesc), len(file_proto_hqssh_proto_rawDesc)))
	})
	return file_proto_hqssh_proto_rawDescData
}

var file_proto_hqssh_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_hqssh_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_hqssh_proto_goTypes = []any{
	(SessionStatus)(0),           // 0: hqssh.SessionStatus
	(TaskScope)(0),               // 1: hqssh.TaskScope
	(TaskRunStatus)(0),           // 2: hqssh.TaskRunStatus
	(*Empty)(nil),                // 3: hqssh.Empty
	(*SystemInfo)(nil),           // 4: hqssh.SystemInfo
	(*SystemStatus)(nil),         // 5: hqssh.SystemStatus
	(*Project)(nil),              // 6: hqssh.Project
	(*ListProjectsRequest)(nil),  // 7: hqssh.ListProjectsRequest
	(*ListProjectsResponse)(nil), // 8: hqssh.ListProjectsResponse
	(*AddProjectRequest)(nil),    // 9: hqssh.AddProjectRequest
	(*RemoveProjectRequest)(nil), // 10: hqssh.RemoveProjectRequest
	(*DiscoverRequest)(nil),      // 11: hqssh.DiscoverRequest
	(*DiscoverResponse)(nil),     // 12: hqssh.DiscoverResponse
	(*GetToolsRequest)(nil),      // 13: hqssh.GetToolsRequest
	(*GetToolsResponse)(nil),     // 14: hqssh.GetToolsResponse
	(*Session)(nil),              // 15: hqssh.Session
	(*CreateSessionRequest)(nil), // 16: hqssh.CreateSessionRequest
	(*ListSessionsRequest)(nil),  // 17: hqssh.ListSessionsRequest
	(*ListSessionsResponse)(nil), // 18: hqssh.ListSessionsResponse
	(*AttachRequest)(nil),        // 19: hqssh.AttachRequest
	(*TerminalOutput)(nil),       // 20: hqssh.TerminalOutput
	(*TerminalInput)(nil),        // 21: hqssh.TerminalInput
	(*DetachRequest)(nil),        // 22: hqssh.DetachRequest
	(*KillSessionRequest)(nil),   // 23: hqssh.KillSessionRequest
	(*ResizeRequest)(nil),        // 24: hqssh.ResizeRequest
	(*Task)(nil),                 // 25: hqssh.Task
	(*TaskRun)(nil),              // 26: hqssh.TaskRun
	(*ListTasksRequest)(nil),     // 27: hqssh.ListTasksRequest
	(*ListTasksResponse)(nil),    // 28: hqssh.ListTasksResponse
	(*CreateTaskRequest)(nil),    // 29: hqssh.CreateTaskRequest
	(*UpdateTaskRequest)(nil),    // 30: hqssh.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),    // 31: hqssh.DeleteTaskRequest
	(*RunTaskRequest)(nil),       // 32: hqssh.RunTaskRequest
	(*GetRunRequest)(nil),        // 33: hqssh.GetRunRequest
	(*ListRunsRequest)(nil),      // 34: hqssh.ListRunsRequest
	(*ListRunsResponse)(nil),     // 35: hqssh.ListRunsResponse
	(*CancelRunRequest)(nil),     // 36: hqssh.CancelRunRequest
	(*ExportTaskRequest)(nil),    // 37: hqssh.ExportTaskRequest
	(*ExportTaskResponse)(nil),   // 38: hqssh.ExportTaskResponse
	(*ImportTaskRequest)(nil),    // 39: hqssh.ImportTaskRequest
}
var file_proto_hqssh_proto_depIdxs = []int32{
	6,  // 0: hqssh.ListProjectsResponse.projects:type_name -> hqssh.Project
	6,  // 1: hqssh.DiscoverResponse.discovered:type_name -> hqssh.Project
	0,  // 2: hqssh.Session.status:type_name -> hqssh.SessionStatus
	15, // 3: hqssh.ListSessionsResponse.sessions:type_name -> hqssh.Session
	1,  // 4: hqssh.Task.scope:type_name -> hqssh.TaskScope
	2,  // 5: hqssh.TaskRun.status:type_name -> hqssh.TaskRunStatus
	1,  // 6: hqssh.ListTasksRequest.scope:type_name -> hqssh.TaskScope
	25, // 7: hqssh.ListTasksResponse.tasks:type_name -> hqssh.Task
	1,  // 8: hqssh.CreateTaskRequest.scope:type_name -> hqssh.TaskScope
	1,  // 9: hqssh.UpdateTaskRequest.scope:type_name -> hqssh.TaskScope
	26, // 10: hqssh.ListRunsResponse.runs:type_name -> hqssh.TaskRun
	3,  // 11: hqssh.SystemService.GetInfo:input_type -> hqssh.Empty
	3,  // 12: hqssh.SystemService.GetStatus:input_type -> hqssh.Empty
	7,  // 13: hqssh.ProjectService.List:input_type -> hqssh.ListProjectsRequest
	9,  // 14: hqssh.ProjectService.Add:input_type -> hqssh.AddProjectRequest
	10, // 15: hqssh.ProjectService.Remove:input_type -> hqssh.RemoveProjectRequest
	11, // 16: hqssh.ProjectService.Discover:input_type -> hqssh.DiscoverRequest
	13, // 17: hqssh.ProjectService.GetTools:input_type -> hqssh.GetToolsRequest
	16, // 18: hqssh.SessionService.Create:input_type -> hqssh.CreateSessionRequest
	17, // 19: hqssh.SessionService.List:input_type -> hqssh.ListSessionsRequest
	19, // 20: hqssh.SessionService.Attach:input_type -> hqssh.AttachRequest
	21, // 21: hqssh.SessionService.Input:input_type -> hqssh.TerminalInput
	22, // 22: hqssh.SessionService.Detach:input_type -> hqssh.DetachRequest
	23, // 23: hqssh.SessionService.Kill:input_type -> hqssh.KillSessionRequest
	24, // 24: hqssh.SessionService.Resize:input_type -> hqssh.ResizeRequest
	27, // 25: hqssh.TaskService.List:input_type -> hqssh.ListTasksRequest
	29, // 26: hqssh.TaskService.Create:input_type -> hqssh.CreateTaskRequest
	30, // 27: hqssh.TaskService.Update:input_type -> hqssh.UpdateTaskRequest
	31, // 28: hqssh.TaskService.Delete:input_type -> hqssh.DeleteTaskRequest
	32, // 29: hqssh.TaskService.Run:input_type -> hqssh.RunTaskRequest
	33, // 30: hqssh.TaskService.GetRun:input_type -> hqssh.GetRunRequest
	34, // 31: hqssh.TaskService.ListRuns:input_type -> hqssh.ListRunsRequest
	36, // 32: hqssh.TaskService.CancelRun:input_type -> hqssh.CancelRunRequest
	37, // 33: hqssh.TaskService.Export:input_type -> hqssh.ExportTaskRequest
	39, // 34: hqssh.TaskService.Import:input_type -> hqssh.ImportTaskRequest
	4,  // 35: hqssh.SystemService.GetInfo:output_type -> hqssh.SystemInfo
	5,  // 36: hqssh.SystemService.GetStatus:output_type -> hqssh.SystemStatus
	8,  // 37: hqssh.ProjectService.List:output_type -> hqssh.ListProjectsResponse
	6,  // 38: hqssh.ProjectService.Add:output_type -> hqssh.Project
	3,  // 39: hqssh.ProjectService.Remove:output_type -> hqssh.Empty
	12, // 40: hqssh.ProjectService.Discover:output_type -> hqssh.DiscoverResponse
	14, // 41: hqssh.ProjectService.GetTools:output_type -> hqssh.GetToolsResponse
	15, // 42: hqssh.SessionService.Create:output_type -> hqssh.Session
	18, // 43: hqssh.SessionService.List:output_type -> hqssh.ListSessionsResponse
	20, // 44: hqssh.SessionService.Attach:output_type -> hqssh.TerminalOutput
	3,  // 45: hqssh.SessionService.Input:output_type -> hqssh.Empty
	3,  // 46: hqssh.SessionService.Detach:output_type -> hqssh.Empty
	3,  // 47: hqssh.SessionService.Kill:output_type -> hqssh.Empty
	3,  // 48: hqssh.SessionService.Resize:output_type -> hqssh.Empty
	28, // 49: hqssh.TaskService.List:output_type -> hqssh.ListTasksResponse
	25, // 50: hqssh.TaskService.Create:output_type -> hqssh.Task
	25, // 51: hqssh.TaskService.Update:output_type -> hqssh.Task
	3,  // 52: hqssh.TaskService.Delete:output_type -> hqssh.Empty
	26, // 53: hqssh.TaskService.Run:output_type -> hqssh.TaskRun
	26, // 54: hqssh.TaskService.GetRun:output_type -> hqssh.TaskRun
	35, // 55: hqssh.TaskService.ListRuns:output_type -> hqssh.ListRunsResponse
	3,  // 56: hqssh.TaskService.CancelRun:output_type -> hqssh.Empty
	38, // 57: hqssh.TaskService.Export:output_type -> hqssh.ExportTaskResponse
	25, // 58: hqssh.TaskService.Import:output_type -> hqssh.Task
	35, // [35:59] is the sub-list for method output_type
	11, // [11:35] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_hqssh_proto_init() }
func file_proto_hqssh_proto_init() {
	if File_proto_hqssh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hqssh_proto_rawDesc), len(file_proto_hqssh_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_hqssh_proto_goTypes,
		DependencyIndexes: file_proto_hqssh_proto_depIdxs,
		EnumInfos:         file_proto_hqssh_proto_enumTypes,
		MessageInfos:      file_proto_hqssh_proto_msgTypes,
	}.Build()
	File_proto_hqssh_proto = out.File
	file_proto_hqssh_proto_goTypes = nil
	file_proto_hqssh_proto_depIdxs = nil
}
